export const rowData = [
  {
    wbc: 1000,
    desc: "site access & developemnt",
    labourHour: "",
    labour: "",
    material: "",
    heading: true,
  },
  {
    wbc: 1100,
    desc: "General Site Development",
    labourHour: 14232,
    labour: 1502861,
    material: 564268,
    subheading: true,
  },
  {
    wbc: 1120,
    desc: "site ditches & safety berms",
    labourHour: 1380,
    labour: 137821,
    material: 987532,
  },
  {
    wbc: 1140,
    desc: "Access roads",
    labourHour: "",
    labour: "",
    material: "",
    subheading: true,
  },
  {
    wbc: 1120,
    desc: "power supply",
    labourHour: "",
    labour: "",
    material: "",
    subheading: true,
  },

  {
    wbc: 7000,
    desc: "services and utilities facilities",
    labourHour: "",
    labour: "",
    material: "",
    heading: true,
  },
  {
    wbc: 7100,
    desc: "hv powers",
    labourHour: "",
    labour: "",
    material: "",
    subheading: true,
  },
  {
    wbc: 7200,
    desc: "site - wide electrical distribution",
    labourHour: 23528,
    labour: 2484551,
    material: 1792465,
    subheading: true,
  },
  {
    wbc: 7140,
    desc: "water systems",
    labourHour: "",
    labour: "",
    material: "",
    subheading: true,
  },
  {
    wbc: 7340,
    desc: "Raw Water",
    labourHour: 11634,
    labour: 1228525,
    material: 565299,
  },
  {
    wbc: 7315,
    desc: "River water",
    labourHour: 6872,
    labour: 7856342,
    material: 758352,
  },
  {
    wbc: 7320,
    desc: "fresh water",
    labourHour: 76835,
    labour: 2384624,
    material: 95745,
  },
  {
    wbc: 8000,
    desc: "infrastructure facilities",
    labourHour: "",
    labour: "",
    material: "",
    heading: true,
  },
  {
    wbc: 8200,
    desc: "on-Site Roads, parking",
    labourHour: "",
    labour: "",
    material: "",
    subheading: true,
  },
  {
    wbc: 8210,
    desc: "Runway roades& ditches",
    labourHour: 230,
    labour: 24331,
    material: 15378,
  },
];
